# Generated by Django 2.0.8 on 2018-09-13 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('response_types', models.CharField(choices=[('RADIO', 'Radio'), ('CHECKLIST', 'Checklist'), ('TEXT', 'Text')], default='TE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('questions', models.ManyToManyField(to='questionnaire.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question')),
                ('response_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.ResponseOption')),
                ('user_Questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.UserQuestionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='response_options',
            field=models.ManyToManyField(blank=True, to='questionnaire.ResponseOption'),
        ),
    ]
